# Generated by Django 2.0.6 on 2018-06-25 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
